FROM ubuntu:20.04
RUN apt-get update && apt-get install -y wget ca-certificates && rm -rf /var/lib/apt/lists/*
RUN wget -q https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_linux_aarch64.tar.gz \
    && tar -xf piper_linux_aarch64.tar.gz \
    && rm piper_linux_aarch64.tar.gz
WORKDIR /piper
ENTRYPOINT ["/piper/piper"]
